language: java
sudo: false
os:
- linux
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle/wrapper/dists"
  - "$HOME/.gradle/caches/jars-3"
  - "$HOME/.gradle/caches/modules-2"
  - "$HOME/.gradle/caches/package-lists"
  - "$HOME/.jdk"
env:
  global:
  - "_JAVA_OPTIONS=-Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts"
install:
- true
script:
- "./gradlew --version"
- "./gradlew --no-daemon --stacktrace --warning-mode=all ${TRAVIS_GRADLE_PROPERTIES} check"
before_cache:
- find $HOME/.gradle/caches -name '*.lock' -delete

